import { NextRequest } from 'next/server';

// pdfkit types are not perfect with ESM; require for reliability on server
// eslint-disable-next-line @typescript-eslint/no-var-requires
const PDFDocument = require('pdfkit');

type Payload = {
  title: string;
  organization: string;
  contactName: string;
  contactEmail: string;
  summary: string;
  objectives: string;
  baselineEmissionsTCO2e: string;
  targetReductionPercent: string;
  timeline: string;
  measures: string;
  budget: string;
  benefits: string;
  risks: string;
  kpis: string;
};

function addSectionTitle(doc: any, text: string) {
  doc.moveDown(0.5);
  doc.fontSize(14).fillColor('#065f46').text(text, { underline: true });
  doc.moveDown(0.35);
  doc.fillColor('#111827');
}

function addKeyValue(doc: any, key: string, value?: string) {
  if (!value) return;
  doc.fontSize(11).fillColor('#374151').text(`${key}: `, { continued: true });
  doc.fillColor('#111827').text(value);
}

function addBullets(doc: any, text?: string) {
  if (!text) return;
  const lines = text.split('\n').map((l) => l.trim()).filter(Boolean);
  for (const line of lines) {
    const normalized = line.replace(/^-+\\s*/, '');
    doc.text(`? ${normalized}`, { indent: 14 });
  }
}

async function documentToBuffer(doc: any): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on('data', (d: Buffer) => chunks.push(d));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    doc.end();
  });
}

export async function POST(req: NextRequest) {
  const body = (await req.json()) as Payload;

  const doc = new PDFDocument({
    size: 'A4',
    margins: { top: 56, bottom: 56, left: 56, right: 56 },
    info: {
      Title: body.title || 'Carbon Footprint Reduction Project',
      Author: body.organization || body.contactName || 'Project Author',
      Subject: 'Carbon footprint reduction proposal',
      Keywords: 'carbon, footprint, emissions, sustainability, ESG, climate',
    },
  });

  // Header
  doc.fontSize(20).fillColor('#111827').text(body.title || 'Carbon Footprint Reduction Project', {
    align: 'left',
  });
  doc.moveDown(0.25);
  doc.fontSize(11).fillColor('#374151');
  const orgLine =
    [body.organization, body.contactName, body.contactEmail].filter(Boolean).join(' ? ');
  if (orgLine) doc.text(orgLine);
  doc.moveDown(0.75);
  doc.lineWidth(1).strokeColor('#e5e7eb').moveTo(doc.page.margins.left, doc.y).lineTo(595 - doc.page.margins.right, doc.y).stroke();
  doc.moveDown(0.75);

  // Summary
  addSectionTitle(doc, 'Executive Summary');
  if (body.summary) {
    doc.fontSize(12).fillColor('#111827').text(body.summary, { align: 'left' });
  } else {
    doc.fontSize(12).fillColor('#6b7280').text('No summary provided.');
  }

  // Objectives
  addSectionTitle(doc, 'Objectives');
  addBullets(doc, body.objectives);

  // Emissions & Targets
  addSectionTitle(doc, 'Baseline & Targets');
  addKeyValue(doc, 'Baseline Emissions (tCO2e)', body.baselineEmissionsTCO2e);
  addKeyValue(doc, 'Target Reduction (%)', body.targetReductionPercent);
  addKeyValue(doc, 'Timeline', body.timeline);

  // Measures
  addSectionTitle(doc, 'Key Measures');
  addBullets(doc, body.measures);

  // Budget
  addSectionTitle(doc, 'Budget');
  if (body.budget) doc.text(body.budget);

  // Benefits
  addSectionTitle(doc, 'Benefits');
  if (body.benefits) doc.text(body.benefits);

  // Risks
  addSectionTitle(doc, 'Risks & Mitigations');
  if (body.risks) doc.text(body.risks);

  // KPIs
  addSectionTitle(doc, 'KPIs');
  addBullets(doc, body.kpis);

  // Footer
  doc.moveDown(1);
  doc.lineWidth(1).strokeColor('#e5e7eb').moveTo(doc.page.margins.left, doc.y).lineTo(595 - doc.page.margins.right, doc.y).stroke();
  doc.moveDown(0.25);
  doc.fontSize(9).fillColor('#6b7280').text('Generated by agentic-0fbae04c', {
    align: 'right',
  });

  const pdfBuffer = await documentToBuffer(doc);
  return new Response(new Uint8Array(pdfBuffer), {
    status: 200,
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="carbon-footprint-project.pdf"`,
      'Cache-Control': 'no-store',
    },
  });
}

